
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: fedadmin
    container_name: fedadmin
    ports:
      - "15000:5000"
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ./data/instance:/app/instance
      - ./data/storage:/app/app/storage
      - ./data/logs:/var/log/fedadmin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"