services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: fedadmin
    container_name: fedadmin
    ports:
      - "5000:5000"
    env_file:
      - .env
    environment:
      # Set to your timezone, e.g., "Europe/London"
      - TZ=Asia/Shanghai
    restart: unless-stopped
    volumes:
      - ./data/instance:/app/instance
      - ./data/storage:/app/app/storage
      - ./data/logs:/var/log/fedadmin
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"