"""Initial migration

Revision ID: 8f3b5150e024
Revises: 
Create Date: 2026-05-15 07:20:49.089885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f3b5150e024'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('federation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_authority', sa.String(length=255), nullable=False),
    sa.Column('registration_policy_url', sa.String(length=255), nullable=False),
    sa.Column('publisher', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organization',
    sa.Column('organization_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('organization_status', sa.Integer(), nullable=False),
    sa.Column('organization_type', sa.Integer(), nullable=False),
    sa.Column('organization_name', sa.String(length=255), nullable=False),
    sa.Column('organization_description', sa.String(length=255), nullable=False),
    sa.Column('organization_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('organization_id')
    )
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_organization_organization_status'), ['organization_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_organization_organization_type'), ['organization_type'], unique=False)

    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('idp',
    sa.Column('idp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idp_status', sa.Integer(), nullable=False),
    sa.Column('idp_name', sa.String(length=255), nullable=False),
    sa.Column('idp_description', sa.String(length=255), nullable=False),
    sa.Column('idp_scope', sa.String(length=255), nullable=False),
    sa.Column('idp_entityid', sa.String(length=255), nullable=False),
    sa.Column('idp_metadata_file', sa.String(length=255), nullable=False),
    sa.Column('idp_logo', sa.String(length=255), nullable=False),
    sa.Column('idp_edugain', sa.Integer(), nullable=False),
    sa.Column('idp_metadata_sha1', sa.String(length=40), nullable=True),
    sa.Column('contact_technical_name', sa.String(length=255), nullable=False),
    sa.Column('contact_technical_email', sa.String(length=255), nullable=False),
    sa.Column('security_contact_name', sa.String(length=255), nullable=False),
    sa.Column('security_contact_email', sa.String(length=255), nullable=False),
    sa.Column('sirtfi_enabled', sa.Boolean(), nullable=False),
    sa.Column('rs_enabled', sa.Boolean(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.PrimaryKeyConstraint('idp_id'),
    sa.UniqueConstraint('idp_entityid')
    )
    with op.batch_alter_table('idp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idp_idp_status'), ['idp_status'], unique=False)

    op.create_table('sp',
    sa.Column('sp_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sp_status', sa.Integer(), nullable=False),
    sa.Column('sp_name', sa.String(length=255), nullable=False),
    sa.Column('sp_description', sa.String(length=255), nullable=False),
    sa.Column('sp_entityid', sa.String(length=255), nullable=False),
    sa.Column('sp_metadata_file', sa.String(length=255), nullable=False),
    sa.Column('sp_logo', sa.String(length=255), nullable=False),
    sa.Column('sp_edugain', sa.Integer(), nullable=False),
    sa.Column('sp_metadata_sha1', sa.String(length=40), nullable=True),
    sa.Column('contact_technical_name', sa.String(length=255), nullable=False),
    sa.Column('contact_technical_email', sa.String(length=255), nullable=False),
    sa.Column('security_contact_name', sa.String(length=255), nullable=False),
    sa.Column('security_contact_email', sa.String(length=255), nullable=False),
    sa.Column('sirtfi_enabled', sa.Boolean(), nullable=False),
    sa.Column('rs_enabled', sa.Boolean(), nullable=False),
    sa.Column('coco_enabled', sa.Boolean(), nullable=False),
    sa.Column('information_url', sa.String(length=255), nullable=False),
    sa.Column('privacy_statement_url', sa.String(length=255), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.PrimaryKeyConstraint('sp_id'),
    sa.UniqueConstraint('sp_entityid')
    )
    with op.batch_alter_table('sp', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sp_sp_status'), ['sp_status'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('fs_uniquifier', sa.String(length=64), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.organization_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('fs_uniquifier'),
    sa.UniqueConstraint('username')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_roles')
    op.drop_table('users')
    with op.batch_alter_table('sp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sp_sp_status'))

    op.drop_table('sp')
    with op.batch_alter_table('idp', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idp_idp_status'))

    op.drop_table('idp')
    op.drop_table('roles')
    with op.batch_alter_table('organization', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_organization_organization_type'))
        batch_op.drop_index(batch_op.f('ix_organization_organization_status'))

    op.drop_table('organization')
    op.drop_table('federation')
    # ### end Alembic commands ###
